### PR TITLE
Slither Setup

### PR DESCRIPTION
**Pull request by brossetti1**
## Description

https://github.com/Network-Goods/hypercerts-protocol/issues/59

- [X] basic setup running slither in separate workflow for now.
- [X] generate serif report and upload

slither run on `brians-starters` - https://github.com/brians-starters/hypercerts-protocol/actions/runs/3896640595/jobs/6653426231

this needs to be ignored for branch to pass: https://github.com/Network-Goods/hypercerts-protocol/pull/86/checks?check_run_id=10590204295

## Potential Additions

- [ ] dependabot as recommended? https://github.com/crytic/slither-action#staying-up-to-date (optinonal)

## Follow Up

@bitbeckers hey so I saw https://github.com/Network-Goods/hypercerts-protocol/issues/59 and thought I could pick it up. wondering if you can provider some feedback:

- do you want this added to the main ci workflow? 
- is this just a pass/fail thing?
- do you want a report somewhere?

I have a basic report printing in the ci right now, I can adjust it however you see fit.

## Code Scanning

Screen Shot 2023-01-11 at 2 40 06 PM

Screen Shot 2023-01-11 at 2 40 12 PM

### CODE REVIEW

**Comment by bitbeckers** [comment]
Oh because you closed the other one I started on the same. My thoughts were to have a separate flow and let it report using the SARIF integrations. With pass/fail you mean it would block merging? But if there are high errors, it would be nice to get a failed task.

I'll stop my efforts on Slither and work on the other test things on the list. 


Once again thanks for contributing!

**Comment by brossetti1** [comment]
@bitbeckers oh hah my bad, i preemptively opened it and closed it. yeah pass/fail would mean it would block merging.

oh man didnt see they have their own action -- ill use that

i can take what youve got and add it to mine (serif integration)

**Comment by brossetti1** [comment]
@bitbeckers this one should be ready to check out -- i did notice that the checks block when there is a `high` slither check caught -- not sure why that works like it does -- might have something to do with the code scanning settings?

anyways, in order to set code scanning up you need to add the default config to the repo -- go to `Settings -> Security Analysis -> Code Scanning`

Screen Shot 2023-01-11 at 2 44 32 PM

**Comment by bitbeckers** [comment]
Nice! A question, I see that you've added this to the main branch. We're developing mostly under `dev` at the moment. I this works I can fork you code into `dev`. But I don't want to steal your thunder, so if possible could you make a PR into `dev`?

Oh, and you can ping me on Telegram if the job execution is pending because I don't get notifications for those

**Comment by brossetti1** [comment]
oh yeah, I moved this branch to base of dev -- feel free to ignore the high severity alert (which is coming from within openzepplin so im assuming this is fine) and merge if your satisfied with the setup. thanks @bitbeckers

**Pull request merged**
